// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    Header: typeof import('./src/components/Header.vue')['default']
    InfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    Select: typeof import('./src/components/Select.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}

export { }
